In [0]:
# Description: This programs tells whether email is spam or not

In [0]:
#Import Libraries
import numpy as np
import pandas as pd
import nltk 
from nltk.corpus import stopwords
import string

In [0]:
# Load the data
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [26]:
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails.csv


In [28]:
# Read the CSV file
df = pd.read_csv('emails.csv')
#Print the first five rows of data
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [29]:
#Print the shape (Get the number of rows and columns)
df.shape

(5728, 2)

In [30]:
#Get the column names
df.columns

Index(['text', 'spam'], dtype='object')

In [0]:
#Check for duplicates
df.drop_duplicates(inplace = True)

In [32]:
#New  shape
df.shape

(5695, 2)

In [33]:
#Show missing data for each columns
df.isnull().sum()

text    0
spam    0
dtype: int64

In [34]:
#Download the stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
def process_text(text):
    #What will be covered:
    #1. Remove punctuation
    #2. Remove stopwords
    #3. Return list of clean text words
   #1
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    #2
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    #3
    return clean_words

In [36]:
#Show tokenization
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [0]:
#Convert a collection of text into matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [0]:
#Split the data in 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(messages_bow, df['spam'], test_size=0.20, random_state=0)

In [41]:
#Get shape of message_bow
messages_bow.shape

(5695, 37229)

In [0]:
#Create and train Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, y_train)

In [44]:
#Print the prediction
print(classifier.predict(X_train))

#Print the actual value
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [49]:
#Evaluate the model on training dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train, pred))
print()
print('Confusion Matrix : \n', confusion_matrix(y_train, pred))
print()
print('Accuracy: \n', accuracy_score(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix : 
 [[3445   12]
 [   1 1098]]

Accuracy: 
 0.9971466198419666


In [51]:
#Print the prediction
print(classifier.predict(X_test))

#Print the actual value
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [52]:


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(y_test, pred))
print()
print('Confusion Matrix : \n', confusion_matrix(y_test, pred))
print()
print('Accuracy: \n', accuracy_score(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix : 
 [[862   8]
 [  1 268]]

Accuracy: 
 0.9920983318700615
